### ISSUE TITLE
Possible mistake in example

### ISSUE THREAD

**Issue by benedeki** [danielchabr/pr-has-one-of-labels#5]
I am not very experienced in using actions. but when I used your *PR Labels Checker* per the example:
```
    steps:
      - uses: danielchabr/pr-labels-checker@v3
```
I got errors:
_Unable to resolve action `danielchabr/pr-labels-checker@v3`, unable to find version `v3`_

When I changed to this:
```
    steps:
      - uses: danielchabr/pr-labels-checker@master
```
It started to work like a charm.

**Comment by benedeki** [comment]
P.S.
Would I be sure, what's wrong with v3 I would even have created the PR for the master. But it has consequences...

**Comment by Zejnilovic** [comment]
It should be `danielchabr/pr-labels-checker@v3.0`, the tag is v3.0
